<?php

/**
 * Implements hook_preprocess_page().
 */
function gitam_programme_finder_preprocess_page(&$variables) {
  // Pass dynamic base path to JS
  $variables['#attached']['drupalSettings']['gitamProgrammeFinder']['apiUrl'] = \Drupal::urlGenerator()->generateFromRoute('gitam_programme_finder.ajax_api');
}

/**
 * Implements hook_theme().
 */
function gitam_programme_finder_theme($existing, $type, $theme, $path) {
  return [
    'programme_finder_page' => [
      'variables' => [],
    ],
  ];
}